<a href="https://colab.research.google.com/github/SaswatD27/CS460-NISER-Fall-Semester-2021-22/blob/main/Saswat's_Shot_at_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
nv10=np.zeros(10)
print(nv10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
def npmemorysize(x):
  return x.size*x.itemsize

#an example to show that this works
print(npmemorysize(nv10))

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)
#np.info(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
nv101=np.zeros(10)
nv101[4]=1
print(nv101)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a7=[i for i in range(10,50)]
na7=np.array(a7)
print(na7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
def nparray_rev(vec):
  len1=len(vec)
  return [vec[i] for i in reversed(range(len1))]

#an example
print(nparray_rev(na7))

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr9=np.arange(9).reshape(3,3)
print(arr9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
x=[1,2,0,0,4,0]
l=[]
i=0
for c in x:
    if c!=0:
        l.append(i)
    i+=1
print(l)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
id3=np.identity(3)
print(id3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
rand12=np.random.rand(3,3,3)
print(rand12)

[[[0.85972625 0.69576445 0.8781465 ]
  [0.25757477 0.57980616 0.58576885]
  [0.99832749 0.11438551 0.48057994]]

 [[0.94708136 0.86621511 0.36251267]
  [0.05816956 0.42171714 0.40453279]
  [0.3591683  0.69914512 0.93120329]]

 [[0.28141853 0.17012402 0.12180833]
  [0.92807222 0.51389158 0.32869202]
  [0.41109224 0.79275524 0.31216794]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
rand13=np.random.rand(10,10)
max13, min13= rand13.max(), rand13.min()
print(max13, min13)

0.9893719079298529 0.0013509178271373656


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
rand14=np.random.rand(30)
print(rand14.mean())

0.47378412482047055


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
def fun15(n=10):
    arr=np.zeros((n,n))
    arr[0,:], arr[:,0], arr[-1,:], arr[:,-1]=1, 1, 1, 1
    return arr

print(fun15(10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
def fun16(n=10):
    arr=np.zeros((n,n))
    arr[0,:], arr[:,0], arr[-1,:], arr[:,-1]=0, 0, 0, 0
    return arr

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
0*np.nan
#^ Outputs nan
np.nan==np.nan
#^Outputs False
np.inf>np.nan
#^Outputs False
np.nan - np.nan
#^Outputs nan
np.nan in set([np.nan])
#^Outputs True
0.3 == 3 * 0.1
#^Outputs False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
a18=np.zeros((5,5))
for i in range(4):
  a18[i+1,i]=i+1
print(a18)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
a19=np.zeros((8,8))
for i in range(8):
  for j in range(8):
    if (i+j)%2==1:
      a19[i,j]=1
print(a19)
#OR
a19p=([0,1],[1,0])
a19a=np.tile(a19p,(4,4))
print(a19a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a19p=([0,1],[1,0])
a19a=np.tile(a19p,(4,4))
print(a19a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
a22=np.random.rand(5,5)
print("Original -",a22)
a22=(a22-np.mean(a22))*(1/np.std(a22))
print("Normalised",a22)

Original - [[0.27736377 0.20581118 0.49751713 0.58251503 0.25124306]
 [0.37371848 0.62859525 0.79431095 0.18404945 0.61166038]
 [0.9444707  0.75062863 0.40271179 0.47914189 0.76051449]
 [0.53471991 0.42987712 0.4705618  0.05332875 0.31856888]
 [0.77190341 0.19384158 0.23275855 0.35602652 0.05161048]]
Normalised [[-0.71323332 -1.01532548  0.21624522  0.57510293 -0.82351392]
 [-0.30642766  0.76965174  1.46929669 -1.10720263  0.69815339]
 [ 2.10326509  1.28487173 -0.18401907  0.1386657   1.32660943]
 [ 0.37331386 -0.06932814  0.10244092 -1.65910011 -0.53926703]
 [ 1.37469299 -1.06586065 -0.90155474 -0.38112238 -1.66635456]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
colour = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
a241=np.random.rand(5,3)
a242=np.random.rand(3,2)
print(a241@a242)
#OR
print(np.matmul(a241,a242))

[[0.51597265 0.5723069 ]
 [0.39202856 0.54705641]
 [0.86874534 0.73782902]
 [0.46205119 0.30192252]
 [0.62836978 0.45214893]]
[[0.51597265 0.5723069 ]
 [0.39202856 0.54705641]
 [0.86874534 0.73782902]
 [0.46205119 0.30192252]
 [0.62836978 0.45214893]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
def neg38(a):
  b=np.logical_or((a>8),(a<3))
  print(b)
  c=[]
  for i in range(len(b)):
    if b[i]:
      c.append(1)
    else:
      c.append(-1)
  return c*a

#Test
a=np.array([1,2,3,5,6,4,1,8,9])
print(neg38(a))

[ True  True False False False False  True False  True]
[ 1  2 -3 -5 -6 -4  1 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
#9
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z=np.ones(5)
#Z**Z #legal
#2 << Z >> 2 #illegal
#Z <- Z #legal
#1j*Z #legal
#Z/1/1 #legal
#Z<Z>Z #illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
#np.array(0) / np.array(0) #Undefined division; o/p nan
#np.array(0) // np.array(0) #divide by zero error raised; o/p 0 (why?)
np.array([np.nan]).astype(int).astype(float) #o/p array([-9.22337204e+18]) (why? Some lower bound?)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 8.76642943  9.46268419  5.48851367 -1.15346182  6.67825485 -5.75179296
 -6.4660165  -5.51723675 -4.29465089  7.97359795]
[ 9. 10.  6. -2.  7. -6. -7. -6. -5.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
def com_val(A,B):
  A0=A
  B0=B
  A=np.array(A)
  B=np.array(B)
  C=A-B
  D=[]
  for i in range(len(A)):
    if C[i]==0:
      D.append(A[i])
  return D

print(com_val([1,3,5],[2,3,5]))

[3, 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
#Had to look these up
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
#Coming back to Earth
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
#False; nan!= 1j (iota)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
print("Yesterday - ",np.datetime64('today') - np.timedelta64(1),"\n Today - ",np.datetime64('today')," Tomorrow - ",np.datetime64('today') + np.timedelta64(1))

Yesterday -  2021-09-09 
 Today -  2021-09-10  Tomorrow -  2021-09-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
a36 = np.random.uniform(0,10,10)

print(a36 // 1)
print(a36 - a36%1)
print(np.floor(a36))
print(a36.astype(int))
print(np.trunc(a36))

[6. 6. 9. 6. 6. 0. 0. 8. 7. 6.]
[6. 6. 9. 6. 6. 0. 0. 8. 7. 6.]
[6. 6. 9. 6. 6. 0. 0. 8. 7. 6.]
[6 6 9 6 6 0 0 8 7 6]
[6. 6. 9. 6. 6. 0. 0. 8. 7. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
a37=[]
for i in range(5):
  a37.append([i for i in range(5)])
print(np.array(a37))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
a38=[np.random.randint(10) for i in range(10)]
print(a38)

[3, 1, 1, 8, 3, 8, 6, 7, 5, 8]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
a39=np.linspace(0.1,1,10,endpoint=False)
print(a39)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
a40=np.random.rand(10)
a40.sort()
print(a40)

[0.16262809 0.29424473 0.31447206 0.40234064 0.56378396 0.58352189
 0.62458094 0.89083397 0.97222866 0.98606176]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
#pinched this answer, couldn't do it
a41=np.arange(10)
print(np.add.reduce(a41))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A=np.random.rand(10)
B=np.random.rand(10)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
a43=np.random.rand(10)
a43.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
def car2pol(a44):
  x,y=a44[:,0],a44[:,1]
  r=np.sqrt(x**2+y**2)
  theta=np.arctan(y,x)
  print(r,theta)
  return None

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
a45=np.random.rand(10)
a45[a45.argmax()]=0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
a46 = np.zeros((10,10), [('x',float),('y',float)])
a46['x'], a46['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(a46)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [49]:
X = np.random.rand(10)
Y = np.random.rand(10)
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

49550610766.76219


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
#Had to look this up, the methods and sets I mean
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [51]:
a49=np.random.rand(10,10,10)
print(a49) #duh?

[[[0.62780029 0.75237683 0.14258867 0.09430653 0.11844578 0.28328947
   0.61251844 0.43907185 0.81255279 0.41862689]
  [0.99813171 0.19864172 0.92542756 0.63914628 0.25365299 0.38216419
   0.85439439 0.05330156 0.68146548 0.77534293]
  [0.04226974 0.95135703 0.75525692 0.0681861  0.49200194 0.0455133
   0.0236012  0.94552313 0.16502542 0.38191517]
  [0.56125676 0.36209993 0.09342762 0.89155146 0.8381996  0.53509215
   0.15729163 0.12148799 0.95550535 0.88405307]
  [0.87561686 0.81325841 0.8615463  0.79958409 0.00984681 0.72822826
   0.26705644 0.13871066 0.32827907 0.96559902]
  [0.15820139 0.00667727 0.63367022 0.73046102 0.21525916 0.97813462
   0.74342919 0.29651166 0.49625637 0.47006916]
  [0.16512999 0.86838163 0.48172106 0.62029703 0.5729884  0.68537954
   0.18527666 0.19518449 0.67514526 0.29285641]
  [0.47161514 0.73203853 0.60643674 0.9601311  0.144626   0.89361614
   0.04970274 0.50486965 0.26117079 0.67517041]
  [0.51858864 0.73481405 0.17734499 0.35935632 0.33953868 0.19033

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [55]:
a50 = np.arange(100)
v = np.random.uniform(0,100)
print(v)
print(a50[(np.abs(a50-v)).argmin()])

23.80409850175559
24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [60]:
a51 = np.zeros(10, [ ('position', [ ('x',float,(1,)),('y',float,(1,))]),('colour',[ ('r',float,(1,)),('g',float,(1,)),('b',float,(1,))])])
print(a51)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)